### ISSUE TITLE
Typos in about info

### ISSUE THREAD

**Issue by glpzzz** [cuba-weather/cuba-weather-flutter#17]

**Comment by leynier** [comment]
@glpzzz Currently the information screen has very little text, not like the previous version. But anyway, thank you very much for the warning.

**Comment by leynier** [comment]
![photo_2020-01-19_01-36-48](https://user-images.githubusercontent.com/36774373/72676170-33484d00-3a5c-11ea-8ca6-cb0f2b722aff.jpg)

**Comment by glpzzz** [comment]
The links to GitHub were good

On January 19, 2020 1:37:09 AM GMT-05:00, "Leynier Gutiérrez González" <notifications@github.com> wrote:
>![photo_2020-01-19_01-36-48](https://user-images.githubusercontent.com/36774373/72676170-33484d00-3a5c-11ea-8ca6-cb0f2b722aff.jpg)
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/leynier/cuba-weather-flutter/issues/17#issuecomment-575972467

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by leynier** [comment]
Ok @glpzzz, I'll put it back. Thank you very much for the recommendation!!!

**Comment by leynier** [comment]
@glpzzz Done, the link to the repository returned.

![photo_2020-01-19_03-39-11](https://user-images.githubusercontent.com/36774373/72677717-6810d000-3a6d-11ea-857b-58ae40660b58.jpg)
